### ISSUE TITLE
AttributeError gi.repositoryPango object has no attribute UNDERLINE_SINGLE

### ISSUE THREAD

**Issue by wb8tyw** [wb8tyw/D-Rats#65]
Have a bug reported by a test user of the python3_tyw test branch, using python3 on Ubuntu 20.04.03 LTS

Pango versions involved are unknown.

`02/07/2022 18:37:58:INFO:MainApp:load main window with self config
Traceback (most recent call last):
  File "./d-rats.py", line 257, in <module>
    main()
  File "./d-rats.py", line 235, in main
    app = mainapp.MainApp(safe=args.safe)
  File "/home/riggs498/Ham-Radio/D-Rats/d_rats/mainapp.py", line 385, in
__init__
    self.mainwindow = mainwindow.MainWindow(self)
  File "/home/riggs498/Ham-Radio/D-Rats/d_rats/mainwindow.py", line 92, in
__init__
    self.tabs["chat"] = ChatTab(wtree, config)
  File "/home/riggs498/Ham-Radio/D-Rats/d_rats/ui/main_chat.py", line 427,
in __init__
    spell.prepare_TextBuffer(entry.get_buffer())
  File "/home/riggs498/Ham-Radio/D-Rats/d_rats/spell.py", line 229, in
prepare_TextBuffer
    tag.set_property("underline", Pango.UNDERLINE_SINGLE)
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32,
in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 132, in
__getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Pango' object has no attribute
'UNDERLINE_SINGLE'
riggs498@ThinkPad:~/Ham-Radio/D-Rats$
'`

**Comment by wb8tyw** [comment]
I just tried on my Ubuntu 20.04.3 system that was originally built as an Ubuntu 19 system and upgraded to 20.04.3.

On python2, not gi module was available, so it would not launch.

On python3, d-rats launched and so did the map.  I do not have it configured it yet so do not have any points plotted.

I have so far confirmed though that my instance of d-rats did not ever call the failing routine, and the unit test for spell also does not call the spell.prepare_TextBuffer method.

Further investigation showed that spell checking was not enabled.  This setting is under the "Appearance" setting.  I would have expected it under the chat settings.

This reproduces the bug.

**Comment by maurizioandreotti** [comment]
checked, confirm it's now ok
