### ISSUE TITLE
File transfer

### ISSUE THREAD

**Issue by maurizioandreotti** [wb8tyw/D-Rats#70]
In the Tab "Files", trying to connect to a remote station (KG5GEN-1 on ratflector: k3pdr.dstargateway.org, port 9000)
I don't see anything in the files list, while in the log I see that the remote station responded:
`
rse_blocks: Got a block: DDT2+: 2:2:1 KG5CEN-1->IZ2LXI-X (b'RATflector_list.txt\x1f375 B (2021-08-06 22:12:00)\x1eICS_203_Organization_Assignment.doc\x1f36 KB (2021-08-06 21:31:31)\x1eApollo_Chat.wav\x1f17 KB (2021-08-06 20:32:01)\x1eRunning+Your+Own+Ratflector.pdf\x1f234 KB (2021-08-06 22:18:23)\x1eSession Four Lesson Plan (rev 2).pdf\x1f619 KB (2021-08-06 22:30:09)\x1eEmail Exercise PART 1.txt\x1f726 B (2021-08-06 20:20:06)\x1eD-RATS Training General.pdf\x1f3455 KB (2021-08-06 21:18:51)\x1eEmail Primer.txt\x1f2 KB (2021-08-06 20:19:15)\x1enewemail.wav\x1f6 KB (2021-08-06 21:51:10)\x1eICS+201.xml\x1f634 B (2021-08-06 21:33:33)\x1eD-RATS_Maildrop.pdf\x1f53 KB (2021-08-06 20:22:52)\x1eRadio Settings With D-Rats.pdf\x1f579 KB (2021-08-06 22:04:50)\x1e_lzhuf_1.exe\x1f29 KB (2021-08-06 20:31:47)\x1eraceslgo.jpg\x1f6 KB (2021-08-06 21:56:46)\x1eHow to cure Ratflector fatigue.txt\x1f351 B (2021-08-06 21:29:12)\x1eics_forms_214.pdf\x1f130 KB (2021-08-06 21:33:14)\x1eEmail Exercise Part 2.txt\x1f1 KB (2021-08-06 20:19:51)\x1eAdditional D-Rats Forms.zip\x1f204 KB (2021-10-25 14:59:17)\x1eGetting Started With D-Star And D-Rats.pdf\x1f43 KB (2021-08-06 21:21:46)\x1eGo Kit Checklist-6-08.pdf\x1f104 KB (2021-08-06 21:24:13)\x1eopen-ratflectors.txt\x1f154 B (2021-08-06 21:52:03)\x1eD-RATS software training net.txt\x1f577 B (2021-08-06 20:33:56)\x1emars1.jpg\x1f6 KB (2021-08-06 21:45:18)\x1eQuick Start Guide To D-Rats.pdf\x1f37 KB (2021-08-06 21:55:09)\x1eding.wav\x1f78 KB (2021-08-06 20:21:14)\x1eICS_202_Incident_Objectives.doc\x1f39 KB (2021-08-06 21:30:28)\x1eD-RATS and Fldigi.txt\x1f475 B (2021-08-06 20:33:18)\x1eD-RATS_&_Gmail.pdf\x1f119 KB (2021-08-06 20:24:56)\x1enew file received.wav\x1f36 KB (2021-08-06 21:50:01)\x1eMessage_Handling handout.pdf\x1f125 KB (2021-08-06 21:48:32)\x1eICS_201_Incident_Briefing.doc\x1f29 KB (2021-08-06 21:29:54)\x1eD-rats Setup.txt\x1f853 B (2021-08-06 20:33:44)\x1eICS214_Activity_Log.xml\x1f10 KB (2021-08-06 21:34:41)\x1e-Aspell Windows 10 for D-Rats.txt\x1f2 KB (2021-10-18 07:19:46)\x1eHIPAA.pdf\x1f138 KB (2021-08-06 21:26:30)\x1eQuick Messages and QSTs.txt\x1f710 B (2021-08-06 21:52:45)\x1eMedical terminology.pdf\x1f74 KB (2021-08-06 21:46:31)\x1eFirst Items For New Users.txt\x1f940 B (2021-08-06 20:18:42)\x1eares-logo.jpg\x1f5 KB (2021-08-06 20:32:38)\x1eICS+202.xml\x1f549 B (2021-08-06 21:34:13)\x1eLouisiana GO-TO Frequencies - Sheet1.pdf\x1f44 KB (2021-08-06 21:44:45)\x1eLeague_diamond_color_high.jpg\x1f3 KB (2021-08-06 21:35:46)\x1e-1 D-Star D-Rats DMR CQ100 Echolink Nets Menu.pdf\x1f234 KB (2021-08-06 20:18:17)\x1eRed Alert.wav\x1f9 KB (2021-08-06 22:14:27)\x1eEmail in Outbox.txt\x1f924 B (2021-08-06 20:19:34)\x1eEstablish a WL2K Account.txt\x1f2 KB (2021-08-06 20:18:59)\x1eForm Manager.txt\x1f442 B (2021-08-06 20:21:41)\x1eNHC_Net_Report.xml\x1f1 KB (2021-08-06 21:51:42)\x1eForm Builder.txt\x1f2 KB (2021-08-06 20:21:56)'...[2550])
 `

**Comment by wb8tyw** [comment]
In trying to reproduce the first thing that I run into is:
```text
02/19/2022 16:26:11:INFO:SessionManager:incoming: Received block 1:1 for session `rpc'
Traceback (most recent call last):
  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/ui/main_files.py", line 186, in _file_list_cb
    units_str = units.decode('utf-8', 'replace')
AttributeError: 'str' object has no attribute 'decode'
```
The units object is already a str object so does not need a decode.

**Comment by wb8tyw** [comment]
Next problem is that d-rats is not making sure that the directory to receive the files actually exists.

It is depending on the action of changing the config options to create the directory.  That failed, apparently because I created a nested directory, and that code could not deal with it.

But in reality, since the config file can be edited by an editor, the configuration module should not be the one that makes sure that the download (also an upload) directory exists.

**Comment by wb8tyw** [comment]
Obviously we need better documentation of all the transfer protocols including were things are translated to/from the bytes data type to the internal data types used by the modules.

**Comment by maurizioandreotti** [comment]
confirmed solved
