### ISSUE TITLE
Config - local files string

### ISSUE THREAD

**Issue by maurizioandreotti** [wb8tyw/D-Rats#71]
Changing the local files string to "downloads" folder as a test, I got into d-rats not starting anymore

checking the config file I see that there si an unxpected "b" before the defined string

`download_dir = b'C:\\Users\\mauri\\Downloads'
`

**Comment by wb8tyw** [comment]
The  problem is actually in dplatform.Win32Platform.gui_select_dir method.

This method uses the win32com.shell methods to get the information.

In python, usually shell methods communicate through pipes and the data read from a pipe is a bytes type.

In python 2 the str and bytes types are related as to be mostly interchangeable.

For python3, the str and bytes types are distinct types and need to be converted when a different type is needed.

**Comment by maurizioandreotti** [comment]
Verified, working
