### ISSUE TITLE
Chat TAB - QSTs not sending 

### ISSUE THREAD

**Issue by maurizioandreotti** [wb8tyw/D-Rats#73]
While in the chat tab i can create a QST, 
- double click on it resets the counter but it doesnt send openweather messages 
- waiting the end of the counter the messages (not only openweather) are NOT sent

02/17/2022 22:04:55:INFO:SessionManager:incoming: Received block 0:5 for session `chat'
02/17/2022 22:05:00:INFO:QSTOpenWeather:QST thread still running, not starting another
02/17/2022 22:05:20:INFO:QSTOpenWeather:QST thread still running, not starting another

**Comment by wb8tyw** [comment]
Reproduced:
```text
Traceback (most recent call last):
  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/mainapp.py", line 1298, in __user_send_chat
    self.chat_session(port).write(msg, station)
  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/mainapp.py", line 725, in chat_session
    return self.smgr[portname][0].get_session(lid=1)
KeyError: '4'
```

**Comment by wb8tyw** [comment]
Investigation is more difficult because the traceback is incomplete due to the way that D-rats works.
Documenting here in the hopes it helps in the future.

Adding some print statements before what was line 725 showed that portname is a type string with value of '4', and apparently missing from the self.smgr dict.

So now we need to dump the keys and values in self.sysmgr to see if that gives us more clues to how this works.

Since chat works and QSTs do not, it is likely that the portname parameter used by the QST is wrong, so we will need to look up the calling stack.

**Comment by wb8tyw** [comment]
Related issue, probably a new bug, the locale specific text is being stored for the radio specific port in the config database.
This means is the locale was changed after a qst was added, then the QST is broken.

**Comment by maurizioandreotti** [comment]
text QST are working, 
GPS, GPSA seems to send out stuff (from the terminal, but nothing appers in the chat window or in the logging tab)

RSS and opeweather, are not sent at all 

some capture from the terminal:

02/28/2022 21:06:57:INFO:QSTOpenWeather:QST thread still running, not starting another
02/28/2022 21:07:21:INFO:QSTOpenWeather:QST thread still running, not starting another
02/28/2022 21:07:23:INFO:QSTOpenWeather:QST thread still running, not starting another
02/28/2022 21:07:24:INFO:QSTOpenWeather:QST thread still running, not starting another

(...)
02/28/2022 21:15:46:INFO:QSTCAP:QST thread still running, not starting another
02/28/2022 21:21:24:INFO:QSTEditDialog:defining qst types
02/28/2022 21:21:44:INFO:ChatQST:Reconfigure: Error : unable to get  QST class `RSS'


it also seems that after I added the RSS QST class in the saved QSTs (also closin and openening d-rats) no QSTs get sent anymore

**Comment by wb8tyw** [comment]
I do not have a GPS connected to any of my test systems.
Is that needed for testing a GPS QST?

What settings should be used for an openweather QST?

**Comment by maurizioandreotti** [comment]
hi John

for Openweather QST this is the explanation I had prepared time ago:
https://groups.io/g/d-rats/topic/d_rats_0_3_9_beta_1_renewed/74229577?p=Created,,,20,2,20,0::recentpostdate%2Fsticky,,,20,2,40,74229577

for gps-gpsa... i don't recall having ever used it in the past, just tested
what was happening for this versions


Il giorno mar 1 mar 2022 alle ore 01:16 John E. Malmberg <
***@***.***> ha scritto:

**Comment by maurizioandreotti** [comment]
for GPS QST,

if I add one QST and click it to force the message to be sent using older
d-rats 0.3.9 , i see nothing in the chat or logging tabs but I see this in
the log file:

Transport : Waiting 1.2 sec before transmitting
Transport : Sending warm-up: DDT2-: 0:0:254 !->! (...[8])
Transport : Sending block: DDT2+: 0:1:0 IZ2LXI-X->CQCQCQ
($$CRC87E6,IZ2LXI-X>APRATS,DSTAR*:/124836h4548.03Nx00925.70Ex/ON D-RATS

...[72])
Msgrouting: Running routing loop


using drats_python3-tyw with the same config i see in the console:

03/01/2022 13:51:33:INFO:Transporter:send_frames: Waiting 1.7 sec before
transmitting
03/01/2022 13:51:35:INFO:Transporter:send_frames: Sending warm-up: DDT2-:
0:0:254 !->! (...[8])
03/01/2022 13:51:35:DEBUG:DDT2EncodedFrame:get_packed: seq:0 session:0
type:254
03/01/2022 13:51:35:DEBUG:Transporter:send_frames: Sending block: DDT2+:
0:1:0 IZ2LXI-X->CQCQCQ
(b'$$CRCE733,IZ2LXI-X>APRATS,DSTAR*:/125133h4548.03Nx00925.70Ex/ON
D-RATS\r\n'...[72])

but nothing in the log file or in the chat neither in the log tab of d-rats.
I guess it sends out a GPS / GPSA packet position using the coordinates in
config

Il giorno mar 1 mar 2022 alle ore 01:16 John E. Malmberg <
***@***.***> ha scritto:

**Comment by wb8tyw** [comment]
I tested a GPS QST with the new code.  It did not show up in the Chat window, but did show up in the event log under a sniffer report.   Filed another ticket as the DPRS button generates a traceback in the stdout.
I then tried the GPS-A QST.   There was a difference in the behavior, there was a sniffer message, and also an event log message that it had received a GPS update report.
GPS-A QST sent from master had same behavior.
GPS QST from master also had the position update message in the log.
So sending of GPS QSTs in the new code definitely has a bug.
Receiving GPS QSTs sent from old to the new code is also only getting the sniffer log, and not the position, so also a bug.

I won't be able to test the openweather QST until later in the week.

**Comment by wb8tyw** [comment]
Example of GPS message from existing master branch
`03/02/2022 07:11:15:INFO:Transporter:_parse_gps: Found GPS string: bytearray(b'$GPGGA,071701,3959.381,N,8816.209,W,1,3,0,0,M,0,M,,*7d\r\nWB8TYW-1,BN test of GPS msg  ')
03/02/2022 07:11:15:INFO:NMEAGPSPosition:_parse_GPGGA:  39.596350,-88.163483
03/02/2022 07:11:15:INFO:SessionManager:incoming: Received block 0:0 for session `chat'
03/02/2022 07:11:15:INFO:MainApp:__incoming_gps_fix: APRSIcon missing - forced to: \?
03/02/2022 07:11:15:INFO:MainApp:__incoming_gps_fix: Export to external mapserver not active: False
03/02/2022 07:11:15:INFO:StaticGPSSource:StaticGPSPosition: WB8TYW-1 reporting 39.5963,-88.1635@0 m at 07:11:15
`
Example of a GPS message from python3_tyw branch:
`03/02/2022 07:14:52:INFO:Transporter:_parse_gps: Found GPS string: bytearray(b'$GPGGA,072037,3959.381,N,8816.209,W,1,3,0,0,M,0,M,,*7c\r\nWB8TYW-1,BN test of GPS msg  ')
03/02/2022 07:14:52:INFO:NMEAGPSPosition:_parse_GPGGA:  39.596350,-88.163483
03/02/2022 07:14:52:INFO:SessionManager:incoming: Received block 0:0 for session `chat'
03/02/2022 07:14:52:INFO:MainApp:__incoming_gps_fix: APRSIcon missing - forced to: \?
03/02/2022 07:14:52:INFO:MainApp:__incoming_gps_fix: Export to external mapserver not active: False
03/02/2022 07:14:52:INFO:StaticGPSSource:StaticGPSPosition: WB8TYW-1 reporting 39.5963,-88.1635@0 m at 07:14:52
`
This time I got the position reporting event log message only for the python3_tyw sent message.

**Comment by wb8tyw** [comment]
Having gone through the code, I can not find a reason other than I may have missed seeing an entry in the event log for the position reports not to be loggged.

As near as I can tell GPS and GPSA QSTs sending and receiving are working properly, except that sometimes for unknown reasons, I do not see a number of the position reports in the event log, even though I see that GPS/GPSA QSTs were decoded.   And unfortunately it is not something that I am able to reproduce on demand.   The missing messages in the event log window means one of these things:

- They are there, but I did not see them
- The signal to write them into the event log  window got lost.  Unlikely as more things would be broken.
- Something is not correct in the signal handler for writing to the event log.

This may need to be another issue to investigate.

**Comment by wb8tyw** [comment]
Use of openweathermap.org data requires another line added to the D-rats sign on.

"Weather data provided by OpenWeather (TM),  https://openweathermap.org/"

**Comment by wb8tyw** [comment]
QST code needs a python3 fix for URLLIB

```text
03/04/2022 07:32:01:INFO:QSTOpenWeather:Started a thread for QST data...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/qst.py", line 398, in threaded_fire
    msg = self.do_qst()
  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/qst.py", line 593, in do_qst
    urllib.urlencode({'q': s_qst, 'appid': owappid})
AttributeError: module 'urllib' has no attribute 'urlencode'
```

https://stackoverflow.com/questions/28906859/module-has-no-attribute-urlencode

**Comment by wb8tyw** [comment]
Yes, for logging messages, the "b" prefix for that string means that it is of type bytes or bytearray.  Which is what we want for diagnostic type log messages.
On python3 bytes/bytearray are different than type "str' and need to be converted to str type by ".decode()" when needed as a string.
That conversion causes characters like "\r\n" to be rendered, and other non-printing characters to become invisible, which can make debugging harder.

We can control which log messages display data as bytes, and which as string on a case by case basis, just like we can set the log level of the message.
