### ISSUE TITLE
mapwindow - segfault

### ISSUE THREAD

**Issue by maurizioandreotti** [wb8tyw/D-Rats#86]
trying to move the map with the mouse while it was still loading the tiles got me to a segmentaion fault error and complete crash of the application

**Comment by wb8tyw** [comment]
Random segmentation faults are going be difficult to find.

My guess is that there is a resource leak somewhere in the map rendering.

**Comment by wb8tyw** [comment]
This may be related to synchronization issues were multiple threads may be trying to read and write data objects at the same time.

**Comment by wb8tyw** [comment]
Found a review for a change request for another project that links this error message to this issue.
[Gtk-CRITICAL gtk/gtktreeview.c:6680 (validate_visible_area): assertion `has_next' failed.](https://github.com/wb8tyw/D-Rats/issues/91)

I could not find any specific information in that change request that could be directly used to fix it.

In reading the current GTK documentation, we have to make sure that we never call any GTK function or method from inside a python thread, you have to use GLib.idle_add, and this could be a result of breaking that rule somewhere.

**Comment by wb8tyw** [comment]
I have not seen this issue since I fixed the tile download code to not call GTK code inside of a thread, and also wait for map downloads to be idle before doing a queue_draw() call.

**Comment by maurizioandreotti** [comment]
same here, not seen this bug since a while.
