### ISSUE TITLE
Mapwindow - "save visible image" not saving (filename not found)

### ISSUE THREAD

**Issue by maurizioandreotti** [wb8tyw/D-Rats#94]
when i try to save the map with menu

Map -> Export -> save visible image

i get the pop-up to select folder and save but then i get into this error:

![image](https://user-images.githubusercontent.com/7696314/155528249-3bc24c1d-333d-4921-8927-c4a92cc7ca3c.png)

**Comment by wb8tyw** [comment]
I can not reproduce this issue on my Microsoft Windows 7 system or on my Anti-X linux system.

The "Documents" folder in the explorer left pane may be a "Llbrary" folder that consists of multiple folders.
If it is a Library folder, by default it should be set up so that writes go into %HOMEDRIVE%\%HOMEPATH%\<something> as the first path in the list.   The name of <something> has varied with the version of Microsoft Windows.

Try navigating the left pane from the c:\Users\ folder to the Documents folder to see if that helps.

**Comment by maurizioandreotti** [comment]
It happnes on ms windows 10  - the error message seems more one generated
by an "open file" dialog rather than a "save file"...

the same  error  happens also if i try save in c:\, so it doent seem
related to the save path, more as it was looking for that filename to open



Il giorno gio 24 feb 2022 alle ore 15:00 John E. Malmberg <
***@***.***> ha scritto:

**Comment by wb8tyw** [comment]
Try this test program:
`python -m d_rats.dplatform gui`

It should bring up three dialogs in order: Open, Save, and select dir.

**Comment by maurizioandreotti** [comment]
output:
$ python -m d_rats.dplatform gui
02/25/2022 14:45:40:INFO:dplatform:Config dir: C:/Users/mauri/AppData/Roaming/D-RATS-EV
02/25/2022 14:45:40:INFO:dplatform:Default dir: C:/Users/mauri/Desktop
02/25/2022 14:45:40:INFO:dplatform:Log file (foo): C:/Users/mauri/AppData/Roaming/D-RATS-EV/logs/foo.txt
02/25/2022 14:45:40:INFO:dplatform:Serial ports: ['COM3', 'COM5']
02/25/2022 14:45:40:INFO:dplatform:OS Version: Windows 10 (10, 0, 19041, 2, '')
02/25/2022 14:45:48:INFO:Platform:gui_open_file: Failed to get filename: (0, 'GetOpenFileNameW', 'No error message is available')
02/25/2022 14:45:48:INFO:dplatform:Open file: None
02/25/2022 14:45:51:INFO:Platform:gui_save_file: Failed to get filename: (0, 'GetSaveFileNameW', 'No error message is available')
02/25/2022 14:45:51:INFO:dplatform:Save file: None
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:/msys64/mingw64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/dplatform.py", line 887, in <module>
    do_test()
  File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/dplatform.py", line 883, in do_test
    logger.info("Open folder: %s", pform.gui_select_dir("/tmp"))
  File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/dplatform.py", line 781, in gui_select_dir
    fname = shell.SHGetPathFromIDList(pidl)
pywintypes.com_error: (-2147467259, 'Unspecified error', None, None)

**Comment by wb8tyw** [comment]
That is progress.

It looks like you used a different path for the save dialog.
Can you try the same path on the save dialog as is failing in D-Rats?

And also try to create a file in that same directory path that failed from the command line?

**Comment by maurizioandreotti** [comment]
$ python -m d_rats.dplatform gui
02/25/2022 18:49:56:INFO:dplatform:Config dir: C:/Users/mauri/AppData/Roaming/D-RATS-EV
02/25/2022 18:49:56:INFO:dplatform:Default dir: C:/Users/mauri/Desktop
02/25/2022 18:49:56:INFO:dplatform:Log file (foo): C:/Users/mauri/AppData/Roaming/D-RATS-EV/logs/foo.txt
02/25/2022 18:49:56:INFO:dplatform:Serial ports: ['COM3', 'COM5']
02/25/2022 18:49:56:INFO:dplatform:OS Version: Windows 10 (10, 0, 19041, 2, '')
02/25/2022 18:50:11:INFO:dplatform:Open file: C:\Users\mauri\Documents\SLAM - DevOps_20211217a.pptx
02/25/2022 18:50:17:INFO:dplatform:Save file: C:\Users\mauri\Documents\confronto isolanti adesivi.xlsx
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:/msys64/mingw64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/dplatform.py", line 887, in <module>
    do_test()
  File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/dplatform.py", line 883, in do_test
    logger.info("Open folder: %s", pform.gui_select_dir("/tmp"))
  File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/dplatform.py", line 781, in gui_select_dir
    fname = shell.SHGetPathFromIDList(pidl)
pywintypes.com_error: (-2147467259, 'Unspecified error', None, None)

**Comment by maurizioandreotti** [comment]
so... after some tests it came out it is not a bug but a feature of ms antivirus which blocks saving local files from python exec

**Comment by wb8tyw** [comment]
There will be a bugfix coming out of this issue.
Your run of the test program produced an unexpected stack trace dump and I will be submitting a PR with a fix for it.
I do not get that stack trace dump on my system.
